name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: [4.10.2, 4.11.2]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ml/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pin solo5
      run: opam pin -n -y git+https://github.com/mato/solo5#new-toolchain
    - name: Pin ocaml-freestanding
      run: opam pin -n -y git+https://github.com/TheLortex/ocaml-freestanding#mirage-4-staging
    - name: Pin ocaml-gmp
      run: opam pin -n -y git+https://github.com/mirage/ocaml-gmp.git#master
    - name: Dune, global GMP
      run: opam depext -iyt conf-gmp dune
    - name: Compiling example project (host)
      run: opam exec -- dune build @install
    - name: Running tests (host)
      run: opam exec -- dune runtest
    - name: External dependencies for bindings 
      run: opam depext -iyt ocaml-freestanding
    - name: Dune and opam-monorepo
      run: opam install -t -y dune opam-monorepo
    - name: Run opam-monorepo
      run: |
        opam monorepo lock
        opam monorepo pull
    - name: Compiling example project (freestanding)
      run: opam exec -- dune build @install --workspace dune-workspace.freestanding
    - name: Running tests (freestanding)
      run: opam exec -- dune runtest --workspace dune-workspace.freestanding
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ml/setup-ocaml@master
      with:
        ocaml-version: 4.11.2
    - name: Dune, global GMP
      run: opam depext -iyt conf-gmp dune
    - name: Compiling example project
      run: opam exec -- dune build @install
    - name: Running tests
      run: opam exec -- dune runtest
